name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    # Only run on main branch pushes, not PRs
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Only run if Pages is enabled
  check-pages:
    runs-on: ubuntu-latest
    outputs:
      pages-enabled: ${{ steps.check.outputs.enabled }}
    steps:
      - name: Check if Pages is enabled
        id: check
        run: |
          # Check if GitHub Pages is configured
          if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pages" | grep -q '"status"'; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "GitHub Pages is not enabled for this repository"
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-pages
    if: needs.check-pages.outputs.pages-enabled == 'true'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: vue-app/package-lock.json
        
    - name: Install dependencies
      run: |
        cd vue-app
        npm ci
        
    - name: Type check
      run: |
        cd vue-app
        npm run type-check
        
    - name: Build
      run: |
        cd vue-app
        npm run build
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: vue-app/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [check-pages, build]
    if: needs.check-pages.outputs.pages-enabled == 'true'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4